add (-,_,_) unspecified
bitand (-,_,_) unspecified
bitor (-,_,_) unspecified
call (_,-) unspecified
div (-,_,_) unspecified
eq (-,_,_) unspecified
equal (-,_,_) unspecified
getprop (-,_,_) unspecified
leftshift (-,_,_) unspecified
lessthan (-,_,_) unspecified
lessthanequal (-,_,_) unspecified
mod (-,_,_) unspecified
mul (-,_,_) unspecified
new (-,_) unspecified
rightshift (-,_,_) unspecified
setprop (_,_,_) unspecified
sub (-,_,_) unspecified
tailcall (_,-) unspecified
unsignedrightshift (-,_,_) unspecified
error (-,-) unspecified
fixnum (-,-) unspecified
geta (-) unspecified
getarg (-,-,-) unspecified
geterr (-) unspecified
getglobal (-,_) unspecified
getglobalobj (-) unspecified
getlocal (-,-,-) unspecified
instanceof (-,_,_) unspecified
isobject (-,_) unspecified
isundef (-,_) unspecified
jump (-) unspecified
jumpfalse (_,-) unspecified
jumptrue (_,-) unspecified
localcall (-) unspecified
makeclosure (-,-) unspecified
makeiterator (-,_) unspecified
move (-,_) unspecified
newframe (-,-) unspecified
nextpropnameidx (-,_) unspecified
not (-,_) unspecified
number (-,-) unspecified
pushhandler (-) unspecified
seta (_) unspecified
setarg (-,-,_) unspecified
setarray (_,-,_) unspecified
setfl (-) unspecified
setglobal (_,_) unspecified
setlocal (-,-,_) unspecified
specconst (-,-) unspecified
typeof (-,-) unspecified
end () unspecified
localret () unspecified
nop () unspecified
pophandler () unspecified
poplocal () unspecified
ret () unspecified
throw () unspecified
unknown () unspecified
